# Tomcat
server:
  port: 8105
  servlet:
    context-path: /api/auth

# Spring
spring:
  profiles:
    active: dev
  application:
    # 应用名称
    name: yuoj-backend-auth
#  profiles:
#    # 环境配置
#    active: dev
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: 127.0.0.1:8848
      config:
        # 配置中心地址
        server-addr: 127.0.0.1:8848
        # 配置文件格式
        file-extension: yml

knife4j:
  enable: true
